[application]
# App name
name = "poweranalyses"

# The Dioxus platform to default to
default_platform = "web"

# `build` & `serve` output path
out_dir = "public"

# The static resource path
asset_dir = "assets"

# The sub package in the workspace to build by default.
sub_package = "dist"

[web.app]
# HTML title tag content
title = "PowerAnalyses.org"
base_path = ""

[web.watcher]
# When watcher is triggered, regenerate the `index.html`
reload_html = true

# Which files or dirs will be monitored
watch_path = ["app/src", "assets"]

# Dioxus will serve the root page when a route is not found
index_on_404 = true

# Include style or script assets
[web.resource]
# CSS style file
style = ["./style.css"]

# Javascript code file
script = []

[web.resource.dev]
# Same as [web.resource], but for development servers
# If you want to include a file in a dx serve server,
# but not a dx serve --release server, put it here

# CSS style file
style = []

# JavaScript files
script = []

[[web.proxy]]
# Proxies will forward requests to a new service.
backend = "http://localhost:8000/api/"
