name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - run: |
          VERSION="$(date +'%Y-%m-%d %H:%M')"
          sed --in-place "s/<VERSION>/$VERSION/g" index.html
        shell: bash

      - uses: mymindstorm/setup-emsdk@v13

      - uses: dtolnay/rust-toolchain@v1
        with:
          target: 'wasm32-unknown-emscripten'
          toolchain: 'stable'
          override: 'true'

      - run: cargo test

      - run: ./script/build.sh

      - uses: actions/upload-artifact@v4
        if: ${{ github.event_name != 'pull_request' }}
        with:
          path: 'public/'
          retention-days: '1'
          overwrite: 'true'

  deploy:
    # Separate step to keep the permissions separated.
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/deploy-pages@v4


