name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions: write-all
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: mymindstorm/setup-emsdk@v11

      - uses: dtolnay/rust-toolchain@e645b0cf01249a964ec099494d38d2da0f0b349f
        with:
          target: wasm32-unknown-emscripten
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: test

      - run: ./script/build.sh

      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name != 'pull_request' }}
        with:
          cname: poweranalyses.org
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          publish_branch: gh-pages
          publish_dir: ./public
