name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3

      - run: |
          VERSION="$(date +'%Y-%m-%d %H:%M')"
          sed --in-place "s/<VERSION>/$VERSION/g" index.html
        shell: bash

      - uses: mymindstorm/setup-emsdk@v11

      - uses: actions-rs/toolchain@v1
        with:
          target: wasm32-unknown-emscripten
          toolchain: stable
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: test

      - run: ./script/build.sh

      - uses: cloudflare/wrangler-action@2.0.0
        if: ${{ github.event_name != 'pull_request' }}
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages publish public --project-name=poweranalyses --branch=main
