name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add release date to index.html
        run: |
          VERSION="$(date +'%Y-%m-%d %H:%M')"
          sed --in-place "s/<VERSION>/$VERSION/g" index.html
        shell: bash

      - name: Setup emscripten SDK
        uses: mymindstorm/setup-emsdk@v13

      - name: Setup Stable Rust with emscripten target
        uses: dtolnay/rust-toolchain@v1
        with:
          target: 'wasm32-unknown-emscripten'
          toolchain: 'stable'

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Build site
        run: ./script/build.sh

      - name: Copy compiled WASM to public
        run: ./script/public.sh

  deploy:
    runs-on: ubuntu-latest
    # Separate step to keep the permissions separated.
    needs: build
    permissions:
      # For the push to `gh-pages` branch.
      contents: write
      pages: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
